"use client"
import { motion } from 'framer-motion';
import React from 'react';
import SectionHeading from './SectionHeading';
import { useSectionInView } from '@/lib/hooks';
import Image from 'next/image'

const About = () => {
	const ref=useSectionInView('About',15);
    return (
        <motion.section  
        	ref={ref}
        	id='about'
        	className='mb-28 px-3  scroll-mt-28 max-w-[45rem] text-center leading-8 sm:mb-40'
        	initial={{opacity:0,y:100}}
        	animate={{opacity:1,y:0}}
        	transition={{delay:.17}}
        >
        	<SectionHeading>
        		About Me
        	</SectionHeading>
            
            <p className='mb-3'>
				 I'm Manuel, a super passionate Computer Science student and <span className="italic">frontend developer</span> with a knack for <span className="italic">game programming</span> and <span className="italic">YouTube content creation</span>. Currently based in Ghana, I juggle between my love for <span className="italic">coding</span>, <span className="italic">anime binge-watching</span>, and <span className="italic">game development</span>. With anime, Im kindof a newbie and I've only seen a few shows but, It's been great so far. I think creativity shines brightest through the medium, and the stories i've seen have been absolute works of art. Hunter x Hunter, Death-Note, Code Geass, FMAB, Shingeki No Kyojin <span className='italic'>(personal favourite, because I have issues). </span> And I'm Currently watching the new <span className="italic">Solo Leveling,</span> some really cool stuff, loving it. and Oh, and I also looooove JJK. 
				<br/>
				<span className="font-medium">Gojo WILL RETURN,</span>
				<div className='relative w-full h-min overflow-hidden'>
					<div className='reversal-red absolute blur-sm rounded-full right-1/2 translate-x-[150%] w-[64px] h-[50px] bg-gradient-radial to-red-500 from-white top-1/2 -translate-y-1/2'/>
					<div className='amplification-blue absolute blur-sm rounded-full left-1/2 -translate-x-[150%]  w-[64px]  h-[50px] bg-gradient-radial to-blue-500 from-white top-1/2 -translate-y-1/2'/>
					<Image 
						className=' z-10 relative 
							bg-gradient-radial from-purple-200 to-transparent 
						backdrop-blur-[.8rem] m-auto aspect-auto  rounded-full border-l-4 border-r-4 border-l-blue-200 border-r-red-200 shadow-2xl  space-normal object-center shadow-purple-300'
						src='https://cdn3.emoji.gg/emojis/6903-gojode.png'
						alt="Satoru Gojo Rioyk Tenkai"
						width={128}
						height={128}
					/>
				</div>
					<span>... I swear..</span>
					<br/>
					Wait, wasn't this section suppose to be about myself?... oh crapp
				</p>
				<p className=''>
				<span className="font-medium">When I'm not buried in code or lost in the world of anime,</span> you'll find me experimenting with the latest features of <span className="italic">Godot game engine</span> or diving deep into <span className="italic">JavaScript, TypeScript,</span> and <span className="italic">React</span> to craft immersive user experiences. My journey to financial freedom and creative fulfillment drives me to push boundaries, whether I'm debugging complex algorithms or scripting captivating narratives for my YouTube audience. Join me as I embark on this exhilarating adventure of learning, creating, and inspiring others through the power of technology and storytelling.
				</p><br/>
				<p>This sections content was not generated by a large language model, specifically not ChatGPT.</p>

        </motion.section>
    );
};

export default About;
